# Generated by Django 4.2.6 on 2023-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
